### ISSUE TITLE
return the actual result

### ISSUE THREAD

**Issue by aleks-hyf** [mag-da-lenka/hyf-homework#10]
https://github.com/mag-da-lenka/hyf-homework/blob/8d29a0eb213214ed93f7cd691b5a280c00b2d625/javascript/javascript2/week1/script-JS2-1-hw.js#L58

A better practice would be to return the result of the math operation, and not the surrounding output. That part can be done by the caller code.

**Comment by mag-da-lenka** [comment]
I totally get your point but this helps me learn.  Never realized this is something inappropriate, but I will avoid it next time. Thank you :)
