### ISSUE TITLE
heavy calculations inside array index

### ISSUE THREAD

**Issue by aleks-hyf** [mag-da-lenka/hyf-homework#13]
https://github.com/mag-da-lenka/hyf-homework/blob/8d29a0eb213214ed93f7cd691b5a280c00b2d625/javascript/javascript2/week1/script-JS2-1-hw.js#L112

Extract the function generateRandomInteger(length) => and use it here instead of doing everything inline. As discussed in class.

**Comment by mag-da-lenka** [comment]
Yes, I do remember it and I immediately realized it applied to me, too  :> 
Will improve!
