### ISSUE TITLE
Return actual value

### ISSUE THREAD

**Issue by aleks-hyf** [mag-da-lenka/hyf-homework#14]
https://github.com/mag-da-lenka/hyf-homework/blob/8d29a0eb213214ed93f7cd691b5a280c00b2d625/javascript/javascript2/week1/script-JS2-1-hw.js#L116

Return actual value, not the verbal output, that part should be in the console log _outside_ the function.

**Comment by mag-da-lenka** [comment]
Ok, I see your point. Thank you!
