### ISSUE TITLE
function naming

### ISSUE THREAD

**Issue by aleks-hyf** [mag-da-lenka/hyf-homework#16]
https://github.com/mag-da-lenka/hyf-homework/blob/8d29a0eb213214ed93f7cd691b5a280c00b2d625/javascript/javascript2/week1/script-JS2-1-hw.js#L138

Usually if a function name starts with a 'get', it returns something, here you're just console.logging. You can either rename the function to what it's actually doing, OR better yet, have this function return the values and print them out where you're calling it.

**Comment by mag-da-lenka** [comment]
Ok, I will be more careful next time. Thanks you :)
