### ISSUE TITLE
return the object

### ISSUE THREAD

**Issue by aleks-hyf** [mag-da-lenka/hyf-homework#17]
https://github.com/mag-da-lenka/hyf-homework/blob/8d29a0eb213214ed93f7cd691b5a280c00b2d625/javascript/javascript2/week1/script-JS2-1-hw.js#L86

Return the object, not the surrounding text. What if you want to use the same values elsewhere but formatted differently? What if you want to use these values for manipulating the DOM?

**Comment by mag-da-lenka** [comment]
Ok, I see your point.  
1. Text => console.log.  Thank you.
