### ISSUE TITLE
Clever

### ISSUE THREAD

**Issue by aleksd-dfds** [mag-da-lenka/hyf-homework#21]
https://github.com/mag-da-lenka/hyf-homework/blob/d881e6390890596f057a71dad3abb95e100bd2f9/javascript/javascript2/week2/script-JS2-2-hw.js#L264

You give credit to some source on the internet, but do you understand how it works? Also, `allLooped` is a confusing variable name. What is it doing? Bottom line is you should be able to do this exercise without clever tricks first, and then reduce is a nice-to-have.

**Comment by mag-da-lenka** [comment]
...cleaning it now to be pushed again 👍  
Thank you :)
