### ISSUE TITLE
Homework Feedback - JS1 - Week1

### ISSUE THREAD

**Issue by Swapna-Sahu** [mag-da-lenka/hyf-homework#3]
Very nice work 👍 
Its good to use let instead var.
Line 36 - logic is to multiply 7 not 5. But anyways it is just a logic not a real one.
Line 41 and line 43 - you can delete line 41. It is not necessary because you are already showing the value in line 43.

Rest all look good for me but you can use less comment.
But you have really done good job .And I enjoyed reading  :)

**Comment by mag-da-lenka** [comment]
Hi, thank you for your feedback.  Glad there no larger issues.  I know I used a lot of comments but that is just because I copied the assignment to my js file to follow the instructions step by step. Normally, I wouldn't do that.  :)
