### ISSUE TITLE
A bit more useful

### ISSUE THREAD

**Issue by aleks-hyf** [mag-da-lenka/hyf-homework#9]
https://github.com/mag-da-lenka/hyf-homework/blob/8d29a0eb213214ed93f7cd691b5a280c00b2d625/javascript/javascript2/week1/script-JS2-1-hw.js#L34

These comments here are a bit more like documentation, so that's ok. But still don't use github as a scratch book for every successful or failed attempt. We just want to see the final result here.

**Comment by mag-da-lenka** [comment]
Hi Aleks, thanks for your feedback :) 
It is true that I leave a lot of comments and also true they are mostly for myself -while I'm learning. 
Next time my homework will be cleaner. :)
